name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github-sustain", "username": "${{ secrets.MAVEN_PACKAGES_USERNAME }}", "password": "${{ secrets.MAVEN_PACKAGES_TOKEN }}"}]'
      - name: Publish package
        run: mvn --batch-mode -Pgithub deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
